Avoid issue with fuerte.yaml in rosdep

diff --git a/environment/tests/Dockerfile b/environment/tests/Dockerfile
--- a/environment/tests/Dockerfile
+++ b/environment/tests/Dockerfile
@@ -60,4 +60,5 @@ USER tailor
 RUN mkdir -p /home/tailor && \
     usermod -d /home/tailor tailor
 
-RUN rosdep update
+# Rosdep fails for fuerte.yaml, so we need || true to not fail
+RUN rosdep update || true
